### ISSUE TITLE
show more context info when thread panicked

### ISSUE THREAD

**Issue by futurist** [hatoo/http-mitm-proxy#34]
The error shown:

```
thread 'tokio-runtime-worker' panicked at /Users/my/.cargo/registry/src/index.crates.io-6f17d22bba15001f/http-mitm-proxy-0.7.1/src/lib.rs:267:81:
called `Result::unwrap()` on an `Err` value: handshake failure
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at /Users/my/.cargo/registry/src/index.crates.io-6f17d22bba15001f/http-mitm-proxy-0.7.1/src/lib.rs:267:81:
called `Result::unwrap()` on an `Err` value: handshake failure
```

The panic just thrown from simple `unwrap()` call, but lost some context, like current `req.uri()`.

Maybe a simple change can be made as `.expect("more infe: req.uri()")` instead of `unwrap()`?

Like below line:

https://github.com/hatoo/http-mitm-proxy/blob/70d49aacc72766dc5078ab4b62c541466f5c1ffd/src/lib.rs#L267C1-L268C1

**Comment by futurist** [comment]
The panic list that I'm encountered till now:

```
thread 'tokio-runtime-worker' panicked at /Users/jm/.cargo/registry/src/index.crates.io-6f17d22bba15001f/http-mitm-proxy-0.7.1/src/lib.rs:267:81:
uri: https://cloud.xfl.net:443/web_api/scm/api/v2/repos/by_names/?repo_names=icube/devtools/deploy: failed to lookup address information: nodename nor servname provided, or not known
```

```
thread 'tokio-runtime-worker' panicked at /Users/jm/.cargo/registry/src/index.crates.io-6f17d22bba15001f/http-mitm-proxy-0.7.1/src/lib.rs:267:81:
connect uri: https://preview.redd.it:443/kvbkzpiqxc7d1.png?width=640&crop=smart&auto=webp&s=762368dbb181ccd89a8243926a14aee622115f5f: connection closed via error
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
